### PR TITLE
Organization fixes

### LINKED ISSUE #2332: Organization fixes
- [x] don't show the review emails box if it's empty
- [x] show the username of the modifier, show like on other screens
- [x] you are not supposed to be able to edit and empty the short name and title (allows save currently)
- [x] show which fields are optional

### PR DESCRIPTION
**Pull request by Macroz**
Closes #2332

Screenshot_2020-09-18_10-08-56

Screenshot_2020-09-18_10-11-35

# Definition of Done / Review checklist

## Reviewability
- [x] link to issue
- [x] consider adding screenshots for ease of review

## API
- [ ] API is backwards compatible or completely new

## Documentation
- [x] update changelog if necessary

## Testing
- [x] complex logic is unit tested
- [x] valuable features are integration / browser / acceptance tested automatically

## Follow-up
- [x] no critical TODOs left to implement

### CODE REVIEW

File: src/clj/rems/api/organizations.clj [hunk 1]
```diff
@@ -1,22 +1,28 @@
...
   {:success s/Bool
    (s/optional-key :organization/id) s/Str
    (s/optional-key :errors) [s/Any]})
 
 (s/defschema EditOrganizationCommand
-  OrganizationFull)
+  (-> OrganizationFull
+      (dissoc :organization/modifier
+              :organization/last-modifier)
+      (assoc (s/optional-key :organization/owners) [User])))
```
Comment (opqdonut) [inline src/clj/rems/api/organizations.clj:25]: so this is the same as CreateOrganizationCommand?

File: src/clj/rems/db/organizations.clj [hunk 2]
```diff
@@ -35,11 +36,16 @@
 (defn get-organizations-raw []
   (->> (db/get-organizations)
        (map parse-organization)
+       (map #(update % :organization/owners (partial mapv (comp users/get-user :userid))))
+       (map #(update % :organization/modifier (comp users/get-user :userid)))
```
Comment (opqdonut) [inline src/clj/rems/db/organizations.clj:40]: shouldn't this be done in the service layer according to our architecture? also, is this `-raw` any more?

**Review by opqdonut — APPROVED** [review]
I'm fine with resolving my comments in a follow-up PR

File: src/clj/rems/api/organizations.clj (hunk 1 above)
Comment (Macroz) [reply src/clj/rems/api/organizations.clj:25]: Yeah since it is easy to copy that schema to the name. I'll do that. They ended up the same.

File: src/clj/rems/db/organizations.clj (hunk 2 above)
Comment (Macroz) [reply src/clj/rems/db/organizations.clj:40]: I had a look at the others and they seemed to use the `get-user` from `db.users` in the db-layer whereas for e.g. organization we have `join-organization` in the service layer. Here the `UserWithAttributes` schema coercing requires us to load them already at this level.

You are right about the `-raw` that perhaps it's not correct anymore. We can have a think about how we want to continue with this.

**Review by opqdonut — APPROVED** [review]

File: src/clj/rems/db/organizations.clj (hunk 2 above)
Comment (Macroz) [reply src/clj/rems/db/organizations.clj:40]: Let's do this one in another PR once we have the idea. https://github.com/CSCfi/rems/issues/2342
