### PR TITLE
fix: owner as organization owner

### LINKED ISSUE #2850: Owner as organization owner
Making the owner user an organization owner leads to a problem wrt. editing organizations because we don't allow organization owners edit them and the code seems to check that access right first (denying a rightful "super" owner, who is an organization owner too, of editing organization owners).

We have some similar inconsistencies in role handling, and this happens sometimes when new users of REMS are trying out various features. E.g. using the "super" owner to apply and handle applications.

- [ ] make sure owner can always edit organization owners, even if they are an organization owner too

### PR DESCRIPTION
**Pull request by Macroz**
Fixes #2850.

Owner wasn't able to edit organization ownership when they were also
an organization owner themselves.

owner1
owner2

# Checklist for author

Remove items that aren't applicable, check items that are done.

## Reviewability
- [x] Link to issue
- [x] Consider adding screenshots for ease of review

## Backwards compatibility
- [x] API is backwards compatible or completely new

## Documentation
- [x] Update changelog if necessary

## Testing
- [x] Valuable features are integration / browser / acceptance tested automatically

### CODE REVIEW

File: src/clj/rems/api/services/organizations.clj [hunk 1]
```diff
@@ -60,9 +61,10 @@
   (organizations/update-organization! (:organization/id org)
                                       (fn [db-organization]
                                         (let [organization-owners (set (map :userid (:organization/owners db-organization)))
-                                              organization-owner? (contains? organization-owners userid)]
+                                              organization-owner? (contains? organization-owners userid)
+                                              owner? (contains? context/*roles* :owner)]
                                           (merge db-organization
-                                                 (remove-keys (if organization-owner?
+                                                 (remove-keys (if (and organization-owner? (not owner?))
```
Comment (aatkin) [inline src/clj/rems/api/services/organizations.clj:67]: would this be simpler to express as `(if-not owner? ...)`? as in only owner role can update owners but roles can also include other roles (like organization owner)

**Review by aatkin — APPROVED** [review]
looks good to me :+1:

File: src/clj/rems/api/services/organizations.clj (hunk 1 above)
Comment (Macroz) [reply src/clj/rems/api/services/organizations.clj:67]: Hmm, I guess it would. Let's however change this in the issue #2828, where we need to check whether it's an owner or organization owner of the same organization.
