### PR TITLE
Error messages when data fetching fails

### LINKED ISSUE #1637: No error message if loading the application fails
For example visiting http://localhost:3000/#/application/999999 just shows an indefinitely spinning spinner.

### PR DESCRIPTION
**Pull request by luontola**
Closes #1637

Adds proper error handling and HTTP request lifecycle management to the application page. The code is currently specific to the application page and has duplication with application search, but could maybe be extracted to be a reusable data fetcher.

Also adds minimal error handlers everywhere else where they were missing. The messages are not localized because hopefully users don't see them often.

The error message when an application doesn't exist:
Application_-_REMS

# Definition of Done / Review checklist

## Reviewability
- [x] link to issue
- [x] consider adding screenshots for ease of review

## Documentation
- [x] add or update docstrings for namespaces and functions

### CODE REVIEW

File: src/cljs/rems/application.cljs [hunk 1]
```diff
@@ -84,49 +85,42 @@
...
- (fn [id]
    (fetch (str "/api/applications/" id)
-          {:handler #(rf/dispatch [::reload-application-result %])})))
+          {:handler #(rf/dispatch [::fetch-application-result %])
+           :error-handler (comp #(rf/dispatch [::fetch-application-result nil])
+                                (flash-message/default-error-handler :top (text :t.applications/application)))})
+   {:db (update db ::application fetcher/started)}))
+
+(defn- initialize-edit-application [db]
+  (let [application (get-in db [::application :data])
```
Comment (opqdonut) [inline src/cljs/rems/application.cljs]: not sure I like the intermediate :data key

how about storing the fetch status under `::application ::fetch`, or perhaps under `::fetch-application` or something

File: src/cljs/rems/application.cljs [hunk 2]
```diff
@@ -710,21 +701,32 @@
...
-                           :attachment-success attachment-success
-                           :config config
-                           :userid userid}])))
-
+        userid (get-in @(rf/subscribe [:identity]) [:user :eppn])]
+    [:div.container-fluid
+     [document-title (if application
+                       (str (text :t.applications/application) " " (format-application-id config application))
+                       (text :t.applications/application))]
+     ^{:key application-id} ; re-render to clear flash messages when navigating to another application
```
Comment (opqdonut) [inline src/cljs/rems/application.cljs]: nice

File: src/cljs/rems/application.cljs (hunk 1 above)
Comment (opqdonut) [reply src/cljs/rems/application.cljs]: after discussion, let's just go with this for now and see if we can come up with something better later
