### PR TITLE
Fix form editor

### LINKED ISSUE #2399: Changing field type to label after entering info text crashes form editor
to reproduce:
- open form editor
- enter an info text for the field
- change field type to "label", the info text inputs disappear
- click save
- white screen, error in browser js console

### PR DESCRIPTION
**Pull request by Macroz**
Fixes #2399.

I wanted to make the placeholder behave the same as info-text so that nothing is sent to back-end if only blank strings are given. I guess this should not break anything as our tests covered this :shrug:

## Reviewability
- [x] Link to issue

## Documentation
- [x] Update changelog if necessary

## Testing
- [x] Complex logic is unit tested

### CODE REVIEW

File: test/clj/rems/test_browser.clj [hunk 1]
```diff
@@ -1147,8 +1147,7 @@
         (is (= {:form/id form-id
                 :organization {:organization/id "nbn" :organization/name {:fi "NBN" :en "NBN" :sv "NBN"} :organization/short-name {:fi "NBN" :en "NBN" :sv "NBN"}}
                 :form/title "Form editor test"
-                :form/fields [{:field/placeholder {:fi "" :en "" :sv ""}
-                               :field/title {:fi "Description (FI)" :en "Description (EN)" :sv "Description (SV)"}
+                :form/fields [{:field/title {:fi "Description (FI)" :en "Description (EN)" :sv "Description (SV)"}
```
Comment (opqdonut) [inline test/clj/rems/test_browser.clj:1150]: this test could have an empty info-text for some entry, perhaps fld1

**Review by opqdonut — APPROVED** [review]
one suggestion, feel free to merge

**Review by marharyta — APPROVED** [review]
Looks good!

**Review by opqdonut — APPROVED** [review]
