### PR TITLE
Fix bug where DUO MOR-code restriction could crash application fetching

### LINKED ISSUE #3086: DUO: Moratorium field date check fails
If you create a resource with DUO moratorium (MOR) field, when you apply for it and add MOR, then after the autosave the validation fails with the following error:

```
2022-11-10 17:03:24,721 [jetty-handlers-159 frank GET /api/applications/1017] ERROR compojure.api.exception - No implementation of method: :equal? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil
java.lang.IllegalArgumentException: No implementation of method: :equal? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:584)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:576)
	at clj_time.core$eval9555$fn__9729$G__9530__9736.invoke(core.clj:102)
	at rems.ext.duo$check_duo_code.invokeStatic(duo.clj:226)
	at rems.ext.duo$check_duo_code.invoke(duo.clj:203)
	at rems.application.model$validate_duo_match.invokeStatic(model.clj:482)
	```

### PR DESCRIPTION
**Pull request by aatkin**
fixes #3086

- DUO validation had bug where `clj-time.core` comparison functions would fail because `:date` restriction in query-code (applicant duo code) was missing data, leading to providing `nil` to the date comparison. Autosave could trigger this bug immediately, leading to the application page crashing upon selecting `MOR` DUO-code from the list. This is now fixed.

# Checklist for author

Remove items that aren't applicable, check items that are done.

## Reviewability
- [x] Link to issue

## Documentation
- [x] Update changelog if necessary

## Testing
- [x] Valuable features are integration / browser / acceptance tested automatically

### CODE REVIEW

File: test/clj/rems/api/test_applications.clj [hunk 1]
```diff
@@ -2186,10 +2193,15 @@
...
+                                 :duo/id "DUO:0000016"
+                                 :duo/label {:en "genetic studies only"}
+                                 :duo/shorthand "GSO"
+                                 :duo/validation {:errors [] :validity "duo/not-found"}}
+                                {:resource/id res1
                                  :duo/id "DUO:0000024"
                                  :duo/label {:en "publication moratorium"}
                                  :duo/shorthand "MOR"
-                                 :duo/validation {:errors [] :validity "duo/not-found"}}
+                                 :duo/validation {:errors [] :validity "duo/not-compatible"}}
```
Comment (aatkin) [inline test/clj/rems/api/test_applications.clj:2204]: this API test now validates that `:date` restriction can be submitted with no data, and it should not error.

**Review by Macroz — APPROVED** [review]
