### PR TITLE
Fix attachments

### LINKED ISSUE #810: Bug in adding attachment to application
Filling an application, adding attachment
 - [x] error message is shown when adding a new attachment
 - [x] attachment link is not working, when clicking the link the actual attachment should be opened
- [x] page not properly refreshed after attaching

### PR DESCRIPTION
**Pull request by Macroz**
Closes #810

### CODE REVIEW

File: src/cljs/rems/application.cljs [hunk 1]
```diff
@@ -36,9 +36,8 @@
   (let [url (str "#/application?items=" (str/join "," (sort (map :id items))))]
     (dispatch! url)))
 
-(defn navigate-to [id]
-  (dispatch! (str "#/application/" id)))
-
+(defn navigate-to [id & [replace?]]
+  (dispatch! (str "#/application/" id) replace?))
```
Comment (cscwooller) [inline src/cljs/rems/application.cljs]: What is the replace? parameter for?

File: src/clj/rems/db/applications.clj [hunk 2]
```diff
@@ -606,6 +610,19 @@
                           :type content-type
                           :data byte-array})))
 
+(defn remove-attachment!
+  [user-id application-id item-id]
+  (let [form (get-form-for user-id application-id)]
+    (when-not (contains? #{"draft" "returned" "withdrawn"
```
[the remark this answers is not in the document]
Comment (Macroz) [reply src/clj/rems/db/applications.clj]: Extracted helper function `editable?` for this.

File: src/cljs/rems/application.cljs (hunk 1 above)
Comment (Macroz) [reply src/cljs/rems/application.cljs]: Added docstring
