### PR TITLE
Wider admin screen, accessibility fixes

### LINKED ISSUE #2814: Hide invalid edit button
We should hide the edit button from the organization owner if the catalogue item etc. is not theirs to edit. They can access the page and get an error from the API at the moment.

- [x] admin tables
- [ ] details pages

### LINKED ISSUE #3121: Tune column width in Actions
Change application title column in Actions to break into multiple lines like resource column. This looks better on narrow screens.

Also make it possible to break words at `_` and possibly some other special characters.

### LINKED ISSUE #3122: Shorten the resource names
- Possibly the same way as Title that you show the first x number of characters and hide the rest with ... ?

### PR DESCRIPTION
**Pull request by Macroz**
Close #3121
Close #3122 
Close #2814 

Ability to screenshot accessibility problems for #2414 

## Scaling behavior in Actions
actions1
actions2

## Scaling behavior in Catalogue items
catalogue-items1
catalogue-items2

## Organization owner can't edit everything
organizations1
forms1

# Checklist for author

Remove items that aren't applicable, check items that are done.

## Reviewability
- [x] Link to issue
- [x] Consider adding screenshots for ease of review

## Backwards compatibility
- [x] Config is backwards compatible

## Documentation
- [x] Update changelog if necessary
- [x] Components are added to guide page
- [ ] Update docs/ (if applicable)
- [ ] Update manual/ (if applicable)

## Testing
- [x] Valuable features are integration / browser / acceptance tested automatically

## Follow-up
- [x] New tasks are created for pending or remaining tasks

### CODE REVIEW

File: src/clj/rems/css/styles.clj [hunk 1]
```diff
@@ -196,6 +197,9 @@
           :background-color (theme-getx :table-heading-bgcolor :color3)}]
     [:th
      :td
+     ["&:last-child:not(:first-child)"
+      "&:last-child:not(:first-child)"
```
Comment (Macroz) [inline src/clj/rems/css/styles.clj:201]: Duplicated?

File: src/clj/rems/css/styles.clj [hunk 2]
```diff
@@ -647,14 +650,21 @@
...
+                   :flex-direction :row
+                   :flex-wrap :wrap
+                   :gap (u/rem 0.5)
+                   :align-items :center
+                   :justify-content :flex-end}]
+   [:td [:div.commands {:justify-content :flex-start}]]
+   [:th.organization {:white-space :normal
+                      :min-width (u/rem 5.5)}]
+   [:th.active {:white-space :normal
+                :min-width (u/rem 5.5)}]
```
Comment (Macroz) [inline src/clj/rems/css/styles.clj:668]: Is the `white-space: normal` required?

File: src/cljs/rems/administration/forms.cljs [hunk 3]
```diff
@@ -101,13 +114,10 @@
...
                      {:value nil
                       :sort-value 1})
-           :commands {:td [:td.commands
-                           [to-view-form form]
-                           [roles/show-when roles/+admin-write-roles+
-                            [form/edit-button (:form/id form)]
-                            [copy-as-new-form form]
-                            [status-flags/enabled-toggle form #(rf/dispatch [::set-form-enabled %1 %2 [::fetch-forms]])]
-                            [status-flags/archived-toggle form #(rf/dispatch [::set-form-archived %1 %2 [::fetch-forms]])]]]}})
+           :commands {:td [:td
```
Comment (Macroz) [inline src/cljs/rems/administration/forms.cljs:117]: Should use `:display-value`?

File: src/cljs/rems/administration/resources.cljs [hunk 4]
```diff
@@ -83,11 +90,10 @@
                      {:td [:td.active
                            [readonly-checkbox {:value checked?}]]
                       :sort-value (if checked? 1 2)})
-           :commands {:td [:td.commands
-                           [to-view-resource (:id resource)]
-                           [roles/show-when roles/+admin-write-roles+
-                            [status-flags/enabled-toggle resource #(rf/dispatch [::set-resource-enabled %1 %2 [::fetch-resources]])]
-                            [status-flags/archived-toggle resource #(rf/dispatch [::set-resource-archived %1 %2 [::fetch-resources]])]]]}})
+           :commands {:td [:td
```
Comment (Macroz) [inline src/cljs/rems/administration/resources.cljs:93]: Can use `:display-value` here?

File: src/cljs/rems/administration/workflows.cljs [hunk 5]
```diff
@@ -83,12 +92,10 @@
                      {:td [:td.active
                            [readonly-checkbox {:value checked?}]]
                       :sort-value (if checked? 1 2)})
-           :commands {:td [:td.commands
-                           [to-view-workflow (:id workflow)]
-                           [roles/show-when roles/+admin-write-roles+
-                            [workflow/edit-button (:id workflow)]
-                            [status-flags/enabled-toggle workflow #(rf/dispatch [::set-workflow-enabled %1 %2 [::fetch-workflows]])]
-                            [status-flags/archived-toggle workflow #(rf/dispatch [::set-workflow-archived %1 %2 [::fetch-workflows]])]]]}})
+           :commands {:td [:td
```
Comment (Macroz) [inline src/cljs/rems/administration/workflows.cljs:95]: Can use `:display-value` here?

File: src/cljs/rems/application_list.cljs [hunk 6]
```diff
@@ -128,7 +128,7 @@
            :last-activity (let [value (:application/last-activity app)]
                             {:value value
                              :display-value (localize-time value)})
-           :view {:td [:td.view [view-button app]]}})
+           :view {:display-value [:div.commands.justify-content-end [view-button app]]}})
```
Comment (Macroz) [inline src/cljs/rems/application_list.cljs:131]: Could try `commands` component but add `right-align` variant.

File: src/cljs/rems/cart.cljs [hunk 7]
```diff
@@ -62,8 +62,9 @@
   [:tr.cart-item
    [:td.title (get-localized-title item language)]
    [:td.commands
-    [remove-from-cart-button item language]
-    (when apply-button? [apply-button [item] language])]])
+    [:div.commands.justify-content-end
```
Comment (Macroz) [inline src/cljs/rems/cart.cljs:65]: Default is already the end?

File: src/cljs/rems/catalogue.cljs [hunk 8]
```diff
@@ -77,14 +77,14 @@
...
              :name {:value (get-localized-title item language)}
-             :commands {:td [:td.commands
-                             [catalogue-item-more-info item language config]
-                             (when logged-in?
-                               (if (:enable-cart config)
-                                 (if (contains? cart-item-ids (:id item))
-                                   [cart/remove-from-cart-button item language]
-                                   [cart/add-to-cart-button item language])
-                                 (apply-button item language)))]}})
+             :commands {:display-value [:div.commands.justify-content-end
```
Comment (Macroz) [inline src/cljs/rems/catalogue.cljs]: Default is already the end?

File: src/cljs/rems/catalogue.cljs [hunk 9]
```diff
@@ -139,7 +139,7 @@
                               :col-span #(if (:category/id %) 2 1)}
                              {:key :commands
                               :content #(when-not (:category/id %)
-                                          [:div.commands.w-100
+                                          [:div.commands.w-100.justify-content-end
```
Comment (Macroz) [inline src/cljs/rems/catalogue.cljs]: Default is already the end?

File: src/cljs/rems/tree.cljs [hunk 10]
```diff
@@ -179,17 +179,20 @@
...
+                                                        [:div.d-flex.flex-row.w-100.align-items-baseline
+                                                         {:class [(when first-column? (str "pad-depth-" (:depth row 0)))
+                                                                  (when (:expanded? row) "expanded")]}
 
-                                                       (when first-column?
-                                                         (when (seq children)
-                                                           (if (:expanded? row)
-                                                             [:i.pl-1.pr-4.fas.fa-fw.fa-chevron-up]
-                                                             [:i.pl-1.pr-4.fas.fa-fw.fa-chevron-down])))
+                                                         (when first-column?
```
Comment (Macroz) [inline src/cljs/rems/tree.cljs:190]: Redundant condition

File: src/cljs/rems/administration/status_flags.cljs [hunk 11]
```diff
@@ -35,7 +35,7 @@
         label (if enabled?
                 :t.administration/disable
                 :t.administration/enable)]
-    {:id (or id "toggle-enabled")
+    {:id id
```
Comment (Macroz) [inline src/cljs/rems/administration/status_flags.cljs]: Could add "toggle-enabled" as class as this would be consistent with the other buttons.

File: src/cljs/rems/table.cljs [hunk 12]
```diff
@@ -70,6 +70,9 @@
               :key ColumnKey
               ;; Title to show at the top of the column.
               (s/optional-key :title) s/Str
+              ;; ARIA label to show at the top of the column.
+              ;; Defaults to `:title`.
+              (s/optional-key :aria-label) s/Str
```
Comment (Macroz) [inline src/cljs/rems/table.cljs:75]: Could be named `:sr-title` also.

Comment (Macroz) [reply src/cljs/rems/table.cljs:75]: `:screenreader/title`

Comment (Macroz) [reply src/cljs/rems/table.cljs:75]: Refactor `:title` to accept Hiccup and use it.

File: src/clj/rems/css/styles.clj (hunk 2 above)
Comment (Macroz) [reply src/clj/rems/css/styles.clj:668]: Yes, normally `th` is `nowrap` but the word "Organization" is rather long compared to an abbreviated organization name, so we should let it wrap.

File: src/cljs/rems/cart.cljs (hunk 7 above)
Comment (Macroz) [reply src/cljs/rems/cart.cljs:65]: Default for a table is actually start, so for the cart and catalogue we must override it.

File: src/cljs/rems/catalogue.cljs (hunk 9 above)
Comment (Macroz) [reply src/cljs/rems/catalogue.cljs]: Default for a table is actually start, so for the cart and catalogue we must override it.

File: src/cljs/rems/table.cljs (hunk 12 above)
Comment (Macroz) [reply src/cljs/rems/table.cljs:75]: Created note https://github.com/CSCfi/rems/projects/1#card-88590402

File: src/cljs/rems/application_list.cljs (hunk 6 above)
Comment (Macroz) [reply src/cljs/rems/application_list.cljs:131]: Added note https://github.com/CSCfi/rems/projects/1#card-88590536

**Review by aatkin — APPROVED** [review]
looks very good! :+1: i noted the few minor minor things i saw, but manual testing didn't reveal issues.

File: src/cljs/rems/atoms.cljs [hunk 13]
```diff
@@ -311,4 +384,40 @@
...
+       (example "empty commands" [commands])
+       (example "with commands"
+
+                (def another-command {:id "another-command"
+                                      :class "another-command"
+                                      :label "Another"
+                                      :url "http://example.com/another"
+                                      :on-click #(js/alert "click another")})
+
+                [commands [action-button example-command another-command]])
```
[the remark this answers is not in the document]
Comment (Macroz) [reply src/cljs/rems/atoms.cljs:413]: This was simply a bug in the example, there should be two separate buttons indeed.
