### PR TITLE
fixes & browser test for catalogue item editor

### LINKED ISSUE #2321: catalogue item editor is broken

### PR DESCRIPTION
**Pull request by opqdonut**
closes #2321

# Definition of Done / Review checklist

## Reviewability
- [x] link to issue

## Documentation
- [ ] update changelog if necessary

## Testing
- [x] valuable features are integration / browser / acceptance tested automatically

### CODE REVIEW

File: src/cljs/rems/administration/organization.cljs [hunk 1]
```diff
@@ -71,13 +71,12 @@
...
-                    (map display-localized-review-email)
-                    (interpose [:br]))
-               {:box? false
-                :solid? true}]
+              [:div
+               [:label (text :t.administration/review-emails)]
+               [:div.solid-group
+                (->> (:organization/review-emails organization)
+                     (map display-localized-review-email)
+                     (interpose [:br]))]]
```
Comment (Macroz) [inline src/cljs/rems/administration/organization.cljs:79]: The original intent here was to move into a direction where our detail views i.e. info-fields could be nested. Also sequences should be handled by rows or maps as tables. I think this moves a bit more to the hand-written direction but clearly there is no complete solution for the nesting yet.

File: resources/translations/fi.edn [hunk 2]
```diff
@@ -92,6 +92,7 @@
                    :license-name "Lisenssin nimi"
                    :licenses "Lisenssit"
                    :modifier "Muokkaaja"
+                   :more-info "Lisätietoja-URL (vapaaehtoinen, puuttuessa käytetään resurssin URN:ää)"
```
Comment (Macroz) [inline resources/translations/fi.edn:95]: Isn't it so that URN is used only if there is no link and resource id looks like a URN? Otherwise no link.

File: CHANGELOG.md [hunk 3]
```diff
@@ -34,6 +34,7 @@ Changes since v2.12
 - Fixed enabling a catalogue item after changing its form. (#2283)
 - Added missing decision text to pdf event list.
 - More compatible CSV reports. Line returns are removed from field values and CSV lines are separated with CRLF. (#2311)
+- Fixed editing a catalogue item. (#2322)
```
Comment (Macroz) [inline CHANGELOG.md:37]: Maybe "Fixed not all fields showing up when editing a catalogue item" ?

**Review by Macroz — APPROVED** [review]

File: src/cljs/rems/administration/organization.cljs (hunk 1 above)
Comment (opqdonut) [reply src/cljs/rems/administration/organization.cljs:79]: yeah... I thought about changing slurp-fields so that it only looks at the immediate children, but that was difficult and would've been fragile in another way

File: resources/translations/fi.edn (hunk 2 above)
Comment (opqdonut) [reply resources/translations/fi.edn:95]: yeah

File: CHANGELOG.md (hunk 3 above)
Comment (opqdonut) [reply CHANGELOG.md:37]: It was completely broken, no fields showed up for me and I couldn't press save

Comment (Macroz) [reply CHANGELOG.md:37]: Ok in that case it's better like it is

File: resources/translations/fi.edn (hunk 2 above)
Comment (Macroz) [reply resources/translations/fi.edn:95]: Maybe the text is slightly misleading now. "vapaaehtoinen, puuttuessa kokeillaan URN"?

File: src/cljs/rems/administration/organization.cljs (hunk 1 above)
Comment (Macroz) [reply src/cljs/rems/administration/organization.cljs:79]: Something to keep in mind for later as the model gets more complex.

File: resources/translations/fi.edn (hunk 2 above)
Comment (opqdonut) [reply resources/translations/fi.edn:95]: I'd rather not try to translate a complex sentence into swedish, but if you insist... :grimacing:

File: src/cljs/rems/administration/organization.cljs (hunk 1 above)
Comment (opqdonut) [reply src/cljs/rems/administration/organization.cljs:79]: I guess one solution would be to look for all the text boxes and then get their labels, instead of looking for form-groups

Comment (opqdonut) [reply src/cljs/rems/administration/organization.cljs:79]: ...in slurp-fields that is

File: resources/translations/fi.edn (hunk 2 above)
Comment (Macroz) [reply resources/translations/fi.edn:95]: This could really use some info text help or link to manual.

Comment (Macroz) [reply resources/translations/fi.edn:95]: Let's keep the description for now.
