### PR TITLE
form validation fixes

### LINKED ISSUE #2578: misc. validation fixes
follow-up to #2551 #2564 #2560 
- [x] fix "all columns must have values" validation message shown to applicant
  - [x] make the link work
  - [x] show the column name
- [x] form editor: fix the validation links for table column fields
- [x] form editor: fix JS crash when trying to save empty form (no name, no org, no title, no fields)

### PR DESCRIPTION
**Pull request by opqdonut**
fixes #2578

# Checklist for author

Remove items that aren't applicable, check items that are done.

## Reviewability
- [x] Link to issue

## Documentation
- [ ] Update changelog if necessary
  - fixes mostly relate to features that are already in the changelog

## Testing
- [ ] Valuable features are integration / browser / acceptance tested automatically
  - the validation code is at most smoke-tested in browser tests, we
  don't verify e.g. the focus logic

### CODE REVIEW

File: src/cljs/rems/administration/create_form.cljs [hunk 1]
```diff
@@ -619,28 +619,29 @@
...
+                                   (text-format error (text :t.administration/organization))))
+
+         (when-let [error (:form/internal-name form-errors)]
+           (format-validation-link "internal-name"
+                                   (text-format error (text :t.administration/internal-name))))
+
+         (for [[lang error] (:form/external-title form-errors)]
+           (format-validation-link (str "external-title-" (name lang))
+                                   (text-format error (str (text :t.administration/external-title)
+                                                           " (" (.toUpperCase (name lang)) ")"))))]
```
Comment (marharyta) [inline src/cljs/rems/administration/create_form.cljs:644]: I think we did discuss this one with @Macroz at some point and he suggested to not modify text in code but rather do it in localisations

File: src/cljs/rems/administration/create_form.cljs [hunk 2]
```diff
@@ -638,9 +638,10 @@
            [:li [:a {:href "#" :on-click (focus-input-field "internal-name")}
                  (text-format (:form/internal-name form-errors) (text :t.administration/internal-name))]])
 
-         (when (:form/external-title form-errors)
-           [:li [:a {:href "#" :on-click (focus-input-field "external-title")}
-                 (text-format (:form/external-title form-errors) (text :t.administration/external-title))]])]
+         (for [[lang error] (:form/external-title form-errors)]
+           (format-validation-link (str "external-title-" (name lang))
+                                   (text-format error (str (text :t.administration/external-title)
+                                                           " (" (.toUpperCase (name lang)) ")"))))]
```
Comment (Macroz) [inline src/cljs/rems/administration/create_form.cljs:644]: Would prefer `str/upper-case` here.

**Review by Macroz — APPROVED** [review]
Looks good!

File: src/cljs/rems/administration/create_form.cljs (hunk 1 above)
Comment (opqdonut) [reply src/cljs/rems/administration/create_form.cljs:644]: I'm repeating the style used in `format-field-validation` above. I agree that it's not that pretty, but at least it's consistent within this ns...

Comment (opqdonut) [reply src/cljs/rems/administration/create_form.cljs:644]: Actually, I have an idea for a small refactor to DRY this out a bit

Comment (marharyta) [reply src/cljs/rems/administration/create_form.cljs:644]: sure, I just pointed that out since it is still fresh in my memory, I am ok with the code otherwise

Comment (Macroz) [reply src/cljs/rems/administration/create_form.cljs:644]: Yes, ideally the parentheses would be in the localization text, however we have not done here so before for these cases.

Comment (marharyta) [reply src/cljs/rems/administration/create_form.cljs:644]: no need to change anything from my side

Comment (opqdonut) [reply src/cljs/rems/administration/create_form.cljs:644]: This whole thing is a bit of a hack, and the root cause seems to be #1334 . The form editor uses this style of localized fields:

```
Title
FI    ____________
EN  ____________
SV  ____________
```

This isn't a problem when showing validation errors next to the fields, but when generating this summary for the top of the page we need to somehow textually identify the subfields for various languages.

This wouldn't be a problem if we used this more verbose style that some other administration pages use:

```
Title (FI) _________
Title (EN) ________
Title (SV) ________
```

Comment (opqdonut) [reply src/cljs/rems/administration/create_form.cljs]: Anyway, I pushed a refactor that at least isolates this string-building logic to one place.

Comment (marharyta) [reply src/cljs/rems/administration/create_form.cljs]: I see your point, I agree

**Review by marharyta — APPROVED** [review]
