### PR TITLE
render validation errors from save-draft

### LINKED ISSUE #2611: rendering validation errors does not work on frontend
validation errors for email and phone number fields don't get rendered nicely

something else might be wrong too, investigate

### PR DESCRIPTION
**Pull request by opqdonut**
fixes #2611

# Checklist for author

Remove items that aren't applicable, check items that are done.

## Reviewability
- [x] Link to issue
- [ ] Consider adding screenshots for ease of review

## Documentation
- [x] Update changelog if necessary

## Testing
- [x] Valuable features are integration / browser / acceptance tested automatically

### CODE REVIEW

File: test/clj/rems/test_browser.clj [hunk 1]
```diff
@@ -226,7 +226,16 @@
...
    (get-attachments {:css "a.attachment-link"}))
   ([selector]
-   (mapv (partial btu/get-element-text-el) (btu/query-all selector))))
+   (mapv btu/get-element-text-el (btu/query-all selector))))
+
+(defn get-validation-summary []
+  (mapv btu/get-element-text-el (btu/query-all {:css "#flash-message-top ul li"})))
+
+(defn get-validation-for-field [label]
+  (let [el (first (btu/query-all [{:css ".fields"}
```
Comment (Macroz) [inline test/clj/rems/test_browser.clj:235]: I think `query` does what this `first ... query-all` does too but since it's not very specific in its description about it maybe it's best to be explicit like you have put here and we have elsewhere.

**Review by Macroz — APPROVED** [review]
Nice!

File: test/clj/rems/test_browser.clj (hunk 1 above)
Comment (opqdonut) [reply test/clj/rems/test_browser.clj:235]: Good point, the query-all was a copy-paste leftover from `fill-form-field`
