### PR TITLE
Fix removing catalogue items from cart on apply

### LINKED ISSUE #1035: applying for an item no longer removes it from the cart

### PR DESCRIPTION
**Pull request by luontola**
Fixes #1035

### CODE REVIEW

File: src/cljs/rems/new_application.cljs [hunk 1]
```diff
@@ -6,8 +6,8 @@
             [rems.util :refer [post!]]))
 
 (defn remove-catalogue-items-from-cart! [catalogue-item-ids]
-  (doseq [i catalogue-item-ids]
-    (rf/dispatch [:rems.cart/remove-item i])))
+  (doseq [id catalogue-item-ids]
+    (rf/dispatch [:rems.cart/remove-item {:id id}])))
```
Comment (opqdonut) [inline src/cljs/rems/new_application.cljs]: why wrap it into `{:id id}` just to destructure it in `::remove-item`?

File: src/cljs/rems/cart.cljs [hunk 2]
```diff
@@ -16,16 +16,12 @@
...
-     (assoc db ::cart cart))))
+   (update db ::cart conj item)))
 
 (rf/reg-event-db
  ::remove-item
  (fn [db [_ item]]
-   (let [cart (->> (::cart db)
-                   (remove (comp #{(:id item)} :id)))]
-     (assoc db ::cart cart))))
+   (update db ::cart #(remove (comp #{(:id item)} :id) %))))
```
Comment (opqdonut) [inline src/cljs/rems/cart.cljs]: this might be aesthetics, but I prefer `(partial = (:id item))`
