### PR TITLE
fix: show localization value instead of key in status change emails

### LINKED ISSUE #550: fix: status localization keyword shown in status change email instead of localized text

### PR DESCRIPTION
**Pull request by tjalkane**
closes #550

### CODE REVIEW

File: src/clj/rems/email.clj [hunk 1]
```diff
@@ -8,6 +8,7 @@
                                get-username]]))
 
 (defn send-mail [to subject msg]
+  (clojure.pprint/pprint (str "subject: " subject "msg: " msg))
```
Comment (opqdonut) [inline src/clj/rems/email.clj]: remove this
