### PR TITLE
Fix/entitlements api 1249

### LINKED ISSUE #1249: Entitlements API does not work for owner and reporter
Entitlements api should:
* [ ] return entitlements for a user when called as an owner (only works for handler now)
* [ ] return entitlement for a user when called as an reporter  (only works for handler now)

### PR DESCRIPTION
**Pull request by Macroz**
Closes #1249

### CODE REVIEW

File: src/clj/rems/api/schema.clj [hunk 1]
```diff
@@ -65,6 +65,7 @@
   {:resource s/Str
    :application-id s/Num
    :start s/Str
+   :end s/Str
```
Comment (opqdonut) [inline src/clj/rems/api/schema.clj]: the tests don't test `:end` at all. what value do we get when the db doesn't have an end date?

Comment (Macroz) [reply src/clj/rems/api/schema.clj]: I think I'll add some date checking here because this is a very valuable API anyway. Even though it may duplicate something of the db level tests.

Comment (Macroz) [reply src/clj/rems/api/schema.clj]: I'll add improved acceptance tests in another PR because we want this fix to be deployed for tomorrow.
