### PR TITLE
Use History API for SPA navigation

### LINKED ISSUE #1258: Use History API for SPA navigation
Currently Secretary  routes are configured to use `#` prefixed URIs, which causes in-page links to not work and requires a hack for the skip navigation link.

- [x] remove https://github.com/CSCfi/rems/blob/1805041cc7ee9395b4610c71c3318950d234c6a1/src/cljs/rems/spa.cljs#L261
- [x] remove https://github.com/CSCfi/rems/blob/1805041cc7ee9395b4610c71c3318950d234c6a1/src/cljs/rems/spa.cljs#L382-L385
- [x] change the backend to serve index.html on 404
  - or better, serve index.html from backend only for the routes which are in the frontend (e.g. parse the routes from `rems/spa.cljs`)

### PR DESCRIPTION
**Pull request by luontola**
Closes #1258

# Definition of Done / Review checklist

## Reviewability
- [x] link to issue

## Documentation
- [x] update changelog if necessary

## Testing
- [x] valuable features are integration / browser / acceptance tested automatically

## Accessibility
- [x] conscious decision about where to move focus after an action

## Follow-up
- [x] no critical TODOs left to implement

### CODE REVIEW

File: src/clj/rems/handler.clj [hunk 1]
```diff
@@ -33,9 +33,11 @@
   (shutdown-agents)
   (log/info "Rems has shut down!"))
 
-(defn not-found-handler [req]
-  (error-page {:status 404
-               :title "Page not found"}))
+(defn not-found-handler [_req]
+  ;; TODO: serve 404 for routes which the frontend doesn't recognize
```
Comment (opqdonut) [inline src/clj/rems/handler.clj]: TODO?

File: src/cljs/rems/new_application.cljs [hunk 2]
```diff
@@ -19,7 +19,7 @@
             {:params {:catalogue-item-ids catalogue-item-ids}
              :handler (fn [response]
                         (remove-catalogue-items-from-cart! catalogue-item-ids)
-                        (application/navigate-to (:application-id response) true))
+                        (replace-url! (str "/application/" (:application-id response))))
```
Comment (opqdonut) [inline src/cljs/rems/new_application.cljs]: why not `navigate!`?

File: src/cljs/rems/spa.cljs [hunk 3]
```diff
@@ -411,13 +399,32 @@
...
+                   (fn [path]
+                     ;; XXX: workaround for Secretary/Accountant considering URLs with different hash to be different pages
+                     (let [url (js/URL. path js/location)
+                           path-without-hash (str (.-pathname url) (.-search url))]
+                       (when-not (= @previous-path path-without-hash)
+                         (reset! previous-path path-without-hash)
+                         (secretary/dispatch! path-without-hash)))))
+    :path-exists? (fn [path]
+                    (let [route (secretary/locate-route path)
+                          not-found-page? (= "*" (secretary/route-value (:route route)))]
```
Comment (opqdonut) [inline src/cljs/rems/spa.cljs]: do we need the not-found-page route if we actively avoid it here?

File: src/cljs/rems/spa.cljs [hunk 4]
```diff
@@ -411,13 +399,32 @@
...
-    (events/listen
-     HistoryEventType/NAVIGATE
-     (fn [event]
-       (js/window.rems.hooks.navigate (.-token event))
-       (secretary/dispatch! (.-token event))))
-    (.setEnabled true)))
+  (events/listen accountant/history
+                 HistoryEventType/NAVIGATE
+                 (fn [event]
+                   (js/window.rems.hooks.navigate (.-token event))))
```
Comment (opqdonut) [inline src/cljs/rems/spa.cljs]: why not combine these two `event/listen` calls? or at least put them next to each other?

File: src/cljs/rems/util.cljs [hunk 5]
```diff
@@ -30,36 +31,38 @@
...
-      401 (rf/dispatch [:unauthorized! current-url])
-      403 (rf/dispatch [:forbidden! current-url])
-      nil)))
+      401 (do
+            (rf/dispatch [:unauthorized! current-url])
+            true)
+      403 (do
+            (rf/dispatch [:forbidden! current-url])
+            true)
+      false)))
```
Comment (opqdonut) [inline src/cljs/rems/util.cljs]: pls document return value. what are the semantics?

File: src/cljs/rems/spa.cljs (hunk 3 above)
Comment (luontola) [reply src/cljs/rems/spa.cljs]: This avoidance is to tell Accountant whether to use SPA navigation for a particular link. Otherwise it'll do a traditional full page reload. The not-found page is still needed when the user arrives to the site using a broken link.

File: src/cljs/rems/spa.cljs (hunk 4 above)
Comment (luontola) [reply src/cljs/rems/spa.cljs]: The first is called when the page is initially loaded, the second is not. I'll add one more comment.

File: src/cljs/rems/new_application.cljs (hunk 2 above)
Comment (luontola) [reply src/cljs/rems/new_application.cljs]: It's to remove the current URL (`/application?items=1`) from the browser history. Otherwise pressing the browser's back button will create a new application.

Comment (luontola) [reply src/cljs/rems/new_application.cljs]: The old method used to take a boolean parameter for switching this behaviour, but I split it into two separate methods (`navigate!` and `replace-url!`).

File: src/clj/rems/handler.clj (hunk 1 above)
Comment (luontola) [reply src/clj/rems/handler.clj]: Created issue #1656 for it.
