### PR TITLE
Email outbox

### LINKED ISSUE #1750: Email poller gets stuck in a loop if one of target email addresses does not work
... resending email to all the previous target addresses.

Consider a retry limit or some other way to not re-send to those addresses that have already been sent to.

### PR DESCRIPTION
**Pull request by luontola**
Closes #1750

# Definition of Done / Review checklist

## Reviewability
- [x] link to issue

## Documentation
- [x] update changelog if necessary
- [ ] add or update docstrings for namespaces and functions
- [x] documentation _at least_ for config options (i.e. docs folder)
- [ ] ADR for major architectural decisions or experiments

## Different installations
- [ ] ~new configuration options added to rems-deploy repository~

## Testing
- [x] complex logic is unit tested
- [x] valuable features are integration / browser / acceptance tested automatically

## Follow-up
- [x] new tasks are created for pending or remaining tasks
- [x] no critical TODOs left to implement

### CODE REVIEW

File: src/clj/rems/api/services/application.clj [hunk 1]
```diff
@@ -0,0 +1,63 @@
+(ns rems.api.services.application
```
[the remark this answers is not in the document]
Comment (opqdonut) [reply src/clj/rems/api/services/application.clj]: hmm actually we have lots of namespaces called application this or application that, could this be something like `rems.api.services.command`?

File: src/clj/rems/poller/email.clj [hunk 2]
```diff
@@ -260,21 +254,28 @@
...
+            (str "failed sending email: " e)))))))
 
 (defn run []
-  (common/run-event-poller ::poller (fn [event]
-                                      (doseq [mail (event-to-emails event)]
-                                        (send-email! mail)))))
+  (doseq [email (email-outbox/get-emails {:remaining-attempts? true})]
+    (if-let [error (send-email! (:email-outbox/email email))]
+      (email-outbox/attempt-failed! (:email-outbox/id email) error)
+      (email-outbox/attempt-succeeded! (:email-outbox/id email)))))
```
Comment (opqdonut) [inline src/clj/rems/poller/email.clj]: could log remaining attempts, or at least when sending failed for the final time

File: src/clj/rems/api/services/application.clj (hunk 1 above)
[the remark this answers is not in the document]
Comment (luontola) [reply src/clj/rems/api/services/application.clj]: That's what I was thinking. `command` sounds like a good name.

[the remark this answers is not in the document]
Comment (luontola) [reply src/clj/rems/api/services/application.clj]: Though we also have `rems.application.commands`

File: src/clj/rems/api/services/command.clj [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+            [rems.form-validation :as form-validation]
+            [rems.poller.email :as email]
+            [rems.util :refer [secure-token]])
+  (:import [org.joda.time Period]))
+
+(defn generate-emails! [new-events]
+  (doseq [event new-events
+          email (email/event-to-emails event)]
+    (email-outbox/put! {:email email
+                        :deadline (-> (time/now) (.plus ^Period (:email-retry-period env)))})))
```
Comment (opqdonut) [inline src/clj/rems/api/services/command.clj]: hmm should this function be in a rems.email ns?

File: src/clj/rems/db/email_outbox.clj [hunk 4]
```diff
@@ -0,0 +1,99 @@
+(ns rems.db.email-outbox
```
Comment (opqdonut) [inline src/clj/rems/db/email_outbox.clj]: this could be folded into the rems.email ns if you decide to create it

File: src/clj/rems/db/email_outbox.clj [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+  (:require [clj-time.core :as time]
+            [clojure.test :refer [deftest is testing]]
+            [rems.db.core :as db]
+            [rems.db.pg-util :refer [pg-interval->joda-duration joda-duration->pg-interval]]
+            [rems.json :as json])
+  (:import [org.joda.time Period Duration DateTime]))
+
+(def ^Duration max-backoff (-> (Period.) (.withHours 12) (.toStandardDuration)))
```
Comment (opqdonut) [inline src/clj/rems/db/email_outbox.clj]: hmm, why is minimum backoff in the db but maximum in the source?

File: src/clj/rems/db/email_outbox.clj [hunk 6]
```diff
@@ -0,0 +1,99 @@
...
+             (next-attempt {:email-outbox/backoff (Duration. 2000)
+                            :email-outbox/deadline (DateTime. 60000000)
+                            :unrelated-keys "should be kept"}
+                           now "the error"))))
+
+    (testing "max backoff reached"
+      (is (= {:email-outbox/latest-attempt now
+              :email-outbox/latest-error "the error"
+              :email-outbox/next-attempt (.plus now max-backoff)
+              :email-outbox/backoff max-backoff
```
Comment (opqdonut) [inline src/clj/rems/db/email_outbox.clj]: I'm interested in the test case where backoff is `(- max-backoff "1 second")` or something like that

File: src/clj/rems/db/email_outbox.clj [hunk 7]
```diff
@@ -0,0 +1,99 @@
...
+                           now "the error"))))
+
+    (testing "deadline reached"
+      (is (= {:email-outbox/latest-attempt now
+              :email-outbox/latest-error "the error"
+              :email-outbox/next-attempt nil ; would have been 3000
+              :email-outbox/backoff (Duration. 4000)
+              :email-outbox/deadline (DateTime. 2999)
+              :unrelated-keys "should be kept"}
+             (next-attempt {:email-outbox/backoff (Duration. 2000)
```
Comment (opqdonut) [inline src/clj/rems/db/email_outbox.clj]: hmm this behaviour means that we might only retry for two days even though the max period is three days

it would perhaps be more predictable to always do the last retry precisely at the deadline?

File: src/clj/rems/poller/email.clj [hunk 8]
```diff
@@ -10,10 +10,9 @@
             [rems.config :refer [env]]
```
Comment (opqdonut) [inline src/clj/rems/poller/email.clj]: rems.poller.email could also be folded into the new rems.email ns

if the result is too large, perhaps something like rems.email.template or rems.email.generate for the event-to-email logic?

**Comment by opqdonut** [comment]
not insisting on the ns refactorings, just thought it would be nice to collect everything email-related under one hood

File: src/clj/rems/db/email_outbox.clj (hunk 4 above)
Comment (Macroz) [reply src/clj/rems/db/email_outbox.clj]: Or make `outbox.cljs` if that is a good direction. I guess we'll have several of these and they'll somewhat replace the poller concept?

**Comment by luontola** [comment]
I'll do the namespace reordering in another PR.

File: src/clj/rems/api/services/command.clj [hunk 9]
```diff
@@ -0,0 +1,65 @@
...
+  (jdbc/execute! db/*db* ["LOCK TABLE application_event IN SHARE ROW EXCLUSIVE MODE"])
+  (let [app (when-let [app-id (:application-id cmd)]
+              (applications/get-unrestricted-application app-id))
+        result (commands/handle-command cmd app command-injections)]
+    (when-not (:errors result)
+      (doseq [event (:events result)]
+        (events/add-event! event))
+      (generate-emails! (:events result))
+      (doseq [cmd (run-process-managers (:events result))]
+        (command! cmd)))
```
[the remark this answers is not in the document]
Comment (luontola) [reply src/clj/rems/api/services/command.clj]: done in #1789
